import type { Metadata } from "next";
import "./../assets/styles/globals.css";
import ScreensIndicator from "@/components/Base/ScreensIndicator";
import StoreProvider from "./storeProvider";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {



    return (
        <html lang="en">
            <head>

            <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/@mdi/font/css/materialdesignicons.min.css"
            ></link>
            </head>
            <StoreProvider>
            <body>
                
                {/* <ScreensIndicator /> */}
                {children}
            </body>
            </StoreProvider>
        </html>
    );
}
